required:
  - rnaseq
  - rnafusion
  - qlucore

properties:
  subsample:
    type: object
    properties:
      threads:
        type: integer
        description: Number of threads to use for subsampling
        default: 12
      target:
        type: integer
        description: Target number of reads for subsampling (approximate)
        default: 100_000_000
      init:
        type: string
        description: Code to run before subsampling FASTQ files
        default: ""

  strandedness:
    type: string
    description: Strandedness of RNA-seq library
    enum:
      - unstranded
      - forward
      - reverse
    default: unstranded

  limitSjdbInsertNsj:
    type: integer
    description: Maximum number of junctions to insert for STAR
    default: 1_000_000

  read_length:
    type: integer
    description: Sample read length
    default: 150

  rnaseq:
    type: object
    oneOf:
    - properties: {skip: {const: true}}
    - allOf:
      - required: [aligner]
      - oneOf:
        - required: [star_index]
        - required: [rsem_index]
      - oneOf:
        - required: [genome]
        - required: [fasta, gtf, gene_bed]

    properties:
      skip:
        type: boolean
        default: false
        description: Skip nf-core/rnaseq

      nf_tag:
        type: string
        description: Tag to use for nf-core/rnaseq
        default: "3.14.0"

      nf_url:
        type: string
        description: URL to use for nf-core/rnaseq
        default: "https://github.com/nf-core/rnaseq"

      genome:
        type: string
        description: Genome reference

      fasta:
        type: path
        description: Path to genome fasta file

      transcript_fasta:
        type: path
        description: Path to transcriptome fasta file

      gtf:
        type: path
        description: Path to genome gtf file

      gene_bed:
        type: path
        description: Path to genome gene bed file

      star_index:
        type: path
        description: Path to STAR genome index

      salmon_index:
        type: path
        description: Path to Salmon genome index

      rsem_index:
        type: path
        description: Path to RSEM genome index

      aligner:
        type: string
        description: RNA-seq aligner
        enum:
          - star_salmon
          - star_rsem

  rnafusion:
    type: object
    oneOf:
    - properties: {skip: {const: true}}
    - required: [genomes_base]
    properties:
      skip:
        type: boolean
        description: Skip nf-core/rnafusion
        default: false

      nf_tag:
        type: string
        description: Tag to use for nf-core/rnafusion
        default: "3.0.1"

      nf_url:
        type: string
        description: URL to use for nf-core/rnafusion
        default: "https://github.com/nf-core/rnafusion"

      genomes_base:
        type: path
        description: Path to rnafusion references

      arriba_standalone:
        type: object
        properties:
          cytobands:
            type: path
            description: Arriba cytobands file for standalone visualisation (Autodetect from nf-core/rnafusion by default)
          protein_domains:
            type: path
            description: Arriba protein domains file for standalone visualisation (Autodetect from nf-core/rnafusion by default)
          annotation:
            type: path
            description: GTF annotation for Arriba standalone visualisation (Autodetect from nf-core/rnafusion by default)
          threads:
            type: integer
            description: Nmber of threads for standalone Arriba visualsation (For samtools index and sort)
            default: 12
          init:
            type: string
            description: Code to run before Arriba standalone visualisation
            default: ""

      tools_cutoff:
        type: integer
        description: Minimum number of callers for fusion to be reported
        default: 1

  qlucore:
    type: object
    oneOf:
    - properties: {skip: {const: true}}
    - required: [starfusion_ref]
    properties:
      skip:
        type: boolean
        default: false
        description: Skip qlucore mapping

      subsample:
        type: object
        properties:
          threads:
            type: integer
            description: Number of threads to use for subsampling
            default: 12
          target:
            type: integer
            description: Target number of reads for subsampling (approximate)
            default: 20_000_000
          fallback_fraction:
            type: number
            description: Fraction of reads to subsample if calculation fails
            default: 0.2
          init:
            type: string
            description: Code to run before subsampling qlucore BAM files
            default: ""

      starfusion_ref:
        type: path
        description: Path to STAR-Fusion reference
